### ISSUE TITLE
Question: Placement of default variables for Data Plane Policing Policies

### ISSUE THREAD

**Issue by therealdoug** [netascode/terraform-aci-nac-aci#125]
Hello, I'm writing a module for Data Plane Policing policies which can be defined as an access_policy.interface_policy (like cdp) to be attached to an interface policy group; or it can be defined as a Tenant policy to be attached to an EPG or L3out logical interface profile.

My question is for the `data_plane_policer_policies` definition in `defaults.yaml` - where would be the best place to place a single defaults definition for something that needs to be under `defaults.apic.access_policies.interface_policies` and `defaults.apic.tenants.policies`.

Should there be a single definition, or should it just be copied to those two locations?

**Comment by therealdoug** [comment]
I believe I may have answered my own question.

Working through the rest of it, I think I'll need two modules, one for tenant and one for access because I can't call a single module from both `aci_access_policies.tf` and `aci_tenants.tf`; and we can't guarantee that `manage_access_policies` and `manage_tenants` will be set to true.

I hate to have two copies of essentially the same module, but I don't see a way around it.  Anyone have some insight/suggestions?

**Comment by andbyrne** [comment]
You can create a single module since the only difference is whether the object is created under `uni/infra` or `uni/tn-<tenant>`. The module could have an input variable for tenant name, and if it's `null`, that could be interpreted as being an access policy.

You can definitely call the same module from both `aci_access_policies.tf` and `aci_tenants.tf`. I would recommend putting the defaults in both relevant locations of the `defaults.yaml` file.

**Comment by therealdoug** [comment]
You are right, I had been staring at it so long it didn't register that I could just change the calling module name but point to the same module source.  Thanks for the helpful reminder!
